### ISSUE TITLE
deezer rpc paused

### ISSUE THREAD

**Issue by nikorue** [Braasileiro/DeezerRPC#12]
whenever i play(or pause) the song the icon says paused in rpc
![image](https://user-images.githubusercontent.com/67581183/128130709-13694147-0ea6-46b7-8f48-d5b621283b7d.png)

the project might be dead, but if anyone comes by 
and sees it, then they'll at least know if they're the only ones having the issue xd

**Comment by EnderGreg** [comment]
I have the same issue since yesterday :/

**Comment by nikorue** [comment]
i'll also add that i am on windows 11 and i'm happy it even works

**Comment by sotpotatis** [comment]
@EnderGreg @nikorue This is because a change in Deezer's UI (you see, new icons). There was a similar issue with another Deezer Discord RPC, the one that PreMiD offers. You can read more about the issue [here](https://github.com/PreMiD/Presences/issues/4201). PreMiD solved it quickly, so a temporary solution can be to use PreMiD instead. It can be found at https://premid.app.

**Comment by Braasileiro** [comment]
Sorry for late response, I'll take a look.
