### ISSUE TITLE
Idea: "Listening to Deezer" instead of "Playing Deezer" in the Discord status bar

### ISSUE THREAD

**Issue by WhyAreLess** [Braasileiro/DeezerRPC#30]
Kinda like how Spotify shows on Discord would be really neat 👍 

![image](https://user-images.githubusercontent.com/20587529/192162197-ae77a125-3229-4e2a-95e9-79ceb6aff271.png)

Also thank you for this RPC i'm honestly amazed how little Deezer cares about adding more social features like RPC to their music streaming platform even if there's a 4 year old topic about it on their forums that is still active lol

**Comment by Braasileiro** [comment]
Not possible in the current state of the Discord API. Only bots can use "Listening" and Spotify itself, which in addition, can show album art on demand.

I'm about to migrate to Spotify because of their lack of communication with the community, even though they have a whole forum for that.

Like you said, 4 years and they left it in the drawer like it was nothing. Something so simple.

It's really frustrating. 😞

**Comment by Braasileiro** [comment]
When the SDK supports this for regular developers I will implement this. I will close this issue for now. Thanks.
