### ISSUE TITLE
Help me !

### ISSUE THREAD

**Issue by AlexodeYT** [Braasileiro/DeezerRPC#31]
Hi, I'm French and I use google translate, so excuse me if everything isn't perfect.
I can't solve the error when starting DeezerRPC "Rich Presence Login Failed". 
![image](https://user-images.githubusercontent.com/91338066/195404980-1e4e6a49-5515-47f7-91c2-da676893b148.png)

I understood that it was necessary to inform the id of the discord client in src/app/app.ts but how after to open the .exe with the modifications of the source code? I would be very happy if you could help me because I support this project enormously and I am very grateful to you for doing this work! 

I tested with normal discord and ptb discord on my other pc and it worked (win 10). On the other hand on my other pc (win 11), with normal discord and discord ptb, it still didn't work.

**Comment by Braasileiro** [comment]
You want to compile the project, do I understand correctly?

If you don't have Node.js installed, you will have to [download](https://nodejs.org/en/download/) and install it.

After cloning the repository, you must enter an [Discord AppId](https://discord.com/developers/applications) in **"src/app/app.ts"** as you already mentioned and in the main project folder you need to download the dependencies with the **"npm install"** command in the console.

To run, use the command "npm start".

To generate a release version there are commands **"npm dist-win"** for Windows, **"npm dist-mac"** for Mac (needs a Mac to compile) and **"dist-linux"** for Linux (AppImage).

All output from release versions will go into the **"dist"** folder.

About Windows 11 I'll have to investigate because here I'm still using Windows 10. Maybe updating the dependencies will solve the problem.

**Comment by AlexodeYT** [comment]
After restarts and tweaks on Windows, everything works! Thanks for your help !

**Comment by DvoraNoob** [comment]
> After restarts and tweaks on Windows, everything works! Thanks for your help !

How do you fix the Rich Presence on Windows 11?
